//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : TUniversity.h
//  @ Date : 12.03.2018
//  @ Author :
//
//
#include<iostream>
#include<string>
#include<vector>
using namespace std;

#include "TStudent.h"
#if !defined(_TUNIVERSITY_H)
#define _TUNIVERSITY_H


class TUniversity {
private:
	vector<TStudent*> students;
public:
	void attach(TStudent* st);
	void detach();
	void printData(int i);
	void setData(int i, string name, int age);
};

#endif  //_TUNIVERSITY_H
