//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : TUniversity.cpp
//  @ Date : 12.03.2018
//  @ Author :
//
//
#include<iostream>
#include<string>
using namespace std;

#include "TUniversity.h"
#include "TStudent.h"

void TUniversity::attach(TStudent* st) {
    students.push_back(st);
}

void TUniversity::detach() {
    students.pop_back();
}

void TUniversity::printData(int i) {
    cout<<students.at(i)->getName()<<endl;
    cout<<students.at(i)->getAge()<<endl;
}

void TUniversity::setData(int i, string name, int age) {
    students.at(i)->setName(name);
    students.at(i)->setAge(age);
}

